version: '3'
services:
  frontend:
    build: ./frontend/.
    ports:
      - "80:80"
  backend:
    build: ./backend/.
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DATABASE: angular
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: angular
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: